### ISSUE TITLE
Link: fatal error lnk1181: unable to open input file 'sqlcipher. Lib'

### ISSUE THREAD

**Issue by Duckweeds7** [Monogi/pysqlcipher3_install_win10#1]
Hello, I encountered the above problem, and I still encountered it after rebuilding according to your way. Did you encounter this problem? And isn't the python you should use to execute setup.py in the last three lines?

**Comment by Duckweeds7** [comment]
Hello, the reason has been found out. There is a mistake in the name of my new folder. Now it has been compiled successfully. Thank you very much.

**Comment by Monogi** [comment]
Sorry, I can't be here often to answer questions.  I am very glad that this helped you.
